// Example 1 workflow: the same txt2img example baked into index.html,
// plus the pre-baked EXAMPLE_FALLBACK_NARRATIONS (id → text).
//
// Exported as a CommonJS-like global so the panel can read it without bundling.

window.__EXAMPLE_1 = (function () {
  const NODES = [
    { id: 1, type: "CheckpointLoaderSimple", title: "CheckpointLoaderSimple", pos: [26, 474],
      size: [315, 98], widgets_values: ["v1-5-pruned-emaonly.ckpt"],
      properties: { "Node name for S&R": "CheckpointLoaderSimple" } },
    { id: 2, type: "CLIPTextEncode", title: "CLIPTextEncode", pos: [413, 389],
      size: [425.28, 180.61], widgets_values: ["text, watermark"],
      properties: { "Node name for S&R": "CLIPTextEncode" } },
    { id: 3, type: "CLIPTextEncode", title: "CLIPTextEncode", pos: [415, 186],
      size: [422.85, 164.31], widgets_values: ["beautiful scenery nature glass bottle landscape, purple galaxy bottle,"],
      properties: { "Node name for S&R": "CLIPTextEncode" } },
    { id: 4, type: "EmptyLatentImage", title: "EmptyLatentImage", pos: [473, 609],
      size: [315, 106], widgets_values: [512, 512, 1],
      properties: { "Node name for S&R": "EmptyLatentImage" } },
    { id: 5, type: "KSampler", title: "KSampler", pos: [863, 186],
      size: [315, 262], widgets_values: [778847685464853, "randomize", 20, 8, "euler", "normal", 1],
      properties: { "Node name for S&R": "KSampler" } },
    { id: 6, type: "VAEDecode", title: "VAEDecode", pos: [1209, 188],
      size: [210, 46], widgets_values: [],
      properties: { "Node name for S&R": "VAEDecode" } },
    { id: 7, type: "SaveImage", title: "SaveImage", pos: [1451, 189],
      size: [210, 270], widgets_values: ["ComfyUI"], properties: {} },
  ];

  const LINKS = [
    { srcId: 1, srcSlot: 1, tgtId: 2, tgtSlot: 0, srcSlotName: "CLIP", tgtSlotName: "clip" },
    { srcId: 1, srcSlot: 1, tgtId: 3, tgtSlot: 0, srcSlotName: "CLIP", tgtSlotName: "clip" },
    { srcId: 1, srcSlot: 0, tgtId: 5, tgtSlot: 0, srcSlotName: "MODEL", tgtSlotName: "model" },
    { srcId: 4, srcSlot: 0, tgtId: 5, tgtSlot: 3, srcSlotName: "LATENT", tgtSlotName: "latent_image" },
    { srcId: 3, srcSlot: 0, tgtId: 5, tgtSlot: 1, srcSlotName: "CONDITIONING", tgtSlotName: "positive" },
    { srcId: 2, srcSlot: 0, tgtId: 5, tgtSlot: 2, srcSlotName: "CONDITIONING", tgtSlotName: "negative" },
    { srcId: 5, srcSlot: 0, tgtId: 6, tgtSlot: 0, srcSlotName: "LATENT", tgtSlotName: "samples" },
    { srcId: 1, srcSlot: 2, tgtId: 6, tgtSlot: 1, srcSlotName: "VAE", tgtSlotName: "vae" },
    { srcId: 6, srcSlot: 0, tgtId: 7, tgtSlot: 0, srcSlotName: "IMAGE", tgtSlotName: "images" },
  ];

  const NARRATIONS = {
    "1": "First, we use the Checkpoint Loader Simple node to load our pre-trained Stable Diffusion model, which contains all the necessary weights for generating images.",
    "2": "This CLIP Text Encode node processes our negative prompt, 'text, watermark', converting it into numerical conditioning. This tells the AI what elements we specifically want to avoid in our final image.",
    "3": "Similarly, this CLIP Text Encode node processes our positive prompt, describing 'beautiful scenery' and a 'purple galaxy bottle'. This is the core instruction telling the AI what kind of image we want to create.",
    "4": "The Empty Latent Image node creates a blank canvas of random noise, sized at 512x512 pixels. This serves as the initial starting point that the model will transform into our desired image.",
    "5": "The KSampler is the main engine of our image generation; it takes all our inputs – the model, prompts, and initial noise – and iteratively denoises the image until it becomes our final output.",
    "6": "After the KSampler finishes, the VAEDecode node takes the compressed latent image and converts it back into a viewable, high-resolution pixel image. This is how we can actually see and use the image generated by the model.",
    "7": "Finally, the Save Image node takes our decoded image and saves it to your computer. You can specify the output folder or a file prefix here.",
    "link_1_1_2_0": "We connect the CLIP model from the Checkpoint Loader to the first CLIP Text Encode node, allowing it to interpret your positive text prompt.",
    "link_1_1_3_0": "Then, connect the same CLIP model to the second CLIP Text Encode node for processing your negative text prompt.",
    "link_1_0_5_0": "Next, we connect the core Stable Diffusion model from the Checkpoint Loader to the KSampler, as this model will guide the image generation process.",
    "link_4_0_5_3": "Connect the initial empty latent image to the KSampler, providing the starting canvas for the image generation process.",
    "link_3_0_5_1": "We link the positive text conditioning from its CLIP Text Encode node to the KSampler's positive conditioning input.",
    "link_2_0_5_2": "Likewise, the negative text conditioning is connected to the KSampler's negative conditioning input.",
    "link_5_0_6_0": "The sampled latent image from the KSampler is then connected to the VAE Decode node to transform it back into a viewable image.",
    "link_1_2_6_1": "We connect the VAE model from the Checkpoint Loader to the VAE Decode node, providing the necessary model to convert the latent image.",
    "link_6_0_7_0": "Finally, the decoded image is sent to the Save Image node, allowing you to preview and save your generated output.",
  };

  // Map of narration id → cached MP3 filename inside extension/audio/
  // (sha256-prefix cache keys from tts-cache/, kept stable so we can ship the files)
  // Computed deterministically by scripts/compute-cache-keys.js — keep in sync.
  const AUDIO_BASENAMES = {
    "1":           "869a903e5fb89f71.mp3",
    "2":           "7ac62e1b3e4f69a0.mp3",
    "3":           "67373c877f07b528.mp3",
    "4":           "5ae87f5aa7e3ef4b.mp3",
    "5":           "dd8104fc312c8b60.mp3",
    "6":           "6a2ee08509b19e2d.mp3",
    "7":           "b8ff5dc06645455b.mp3",
    "link_1_1_2_0": "f4cc181c18079222.mp3",
    "link_1_1_3_0": "a9db5da685a0800e.mp3",
    "link_1_0_5_0": "dac0d6f67a8c26d2.mp3",
    "link_4_0_5_3": "3c0e07e2e484c7ad.mp3",
    "link_3_0_5_1": "d582bc8a78e23329.mp3",
    "link_2_0_5_2": "8529e2e17e74d439.mp3",
    "link_5_0_6_0": "41d97d3a644e7aaf.mp3",
    "link_1_2_6_1": "f97f460618177b37.mp3",
    "link_6_0_7_0": "0a24cee846b0f939.mp3",
  };

  return { NODES, LINKS, NARRATIONS, AUDIO_BASENAMES };
})();
